In [36]:
%load_ext autoreload
%autoreload 2

from datamodule_new_data import TransactionDatasetNewData, TransactionDataModuleNewData
import torch

import numpy as np

import pickle

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [37]:
dm = TransactionDataModuleNewData('../../data/new_data/normal/')

In [38]:
dm.setup('fit')

In [39]:
ds = dm.train_dataloader()

In [40]:
x = next(iter(ds))

In [41]:
x.shape

torch.Size([64, 58, 2])

In [42]:
x

tensor([[[ 9.0000e+00,  1.9210e-01],
         [ 9.0000e+00,  6.5149e-02],
         [ 1.9000e+01,  1.0310e-01],
         ...,
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 8.0000e+00, -6.8750e-02],
         [ 1.0000e+00,  2.2093e-02],
         [ 4.0000e+00,  1.7596e-01],
         ...,
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 1.0000e+00,  1.5338e-01],
         [ 1.0000e+00,  2.0503e-01],
         [ 4.0000e+00,  2.0670e-01],
         ...,
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        ...,

        [[ 3.4000e+01,  4.9391e-02],
         [ 3.4000e+01,  1.6784e-01],
         [ 1.0000e+00,  2.1085e-01],
         ...,
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 9.7000e+01,  2.0900e-01

In [43]:
embed = torch.nn.Embedding(387, 16, 0)

In [68]:
transactions = x[:, :, 1]
mcc = x[:, :, 0].long()

In [69]:
transactions.dim()

2

In [59]:
transactions.unsqueeze_(-1)

tensor([[[ 0.1921],
         [ 0.0651],
         [ 0.1031],
         ...,
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[-0.0688],
         [ 0.0221],
         [ 0.1760],
         ...,
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[ 0.1534],
         [ 0.2050],
         [ 0.2067],
         ...,
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        ...,

        [[ 0.0494],
         [ 0.1678],
         [ 0.2108],
         ...,
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[ 0.2090],
         [-0.7108],
         [-0.6770],
         ...,
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[ 0.1618],
         [ 0.1993],
         [ 0.2037],
         ...,
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]]])

In [60]:
transactions.shape

torch.Size([64, 58, 1])

In [49]:
embed_mcc = embed(mcc)

In [58]:
embed_mcc.shape

torch.Size([64, 58, 16])

In [50]:
embed_mcc.shape

torch.Size([64, 58, 16])

In [65]:
torch.concat((transactions, embed_mcc), -1)

tensor([[ 0.1921,  0.0651,  0.1031,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0688,  0.0221,  0.1760,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.1534,  0.2050,  0.2067,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0494,  0.1678,  0.2108,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.2090, -0.7108, -0.6770,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.1618,  0.1993,  0.2037,  ...,  0.0000,  0.0000,  0.0000]],
       grad_fn=<SelectBackward0>)